title: Lebron vs. Harden
author: Pap Roach
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Lebron is almost single handedly carrying his team this year while James Harden is having one of the best offensive years in history.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
